enum ParticipationStates {
  waiting
  cancelled
  accepted
}
enum UserPrivileges {
  guest
  admin
}
input CreateParticipationInput {
  userId: String!
  eventId: String!
  userPrivilege: UserPrivileges
  state: ParticipationStates
}
input UpdateParticipationInput {
  userPrivilege: UserPrivileges
  state: ParticipationStates
}
type Participation {
  _id: ID!
  user: User!
  event: Event!
  userPrivilege: UserPrivileges
  state: ParticipationStates
}
type Query {
  getParticipations: [Participation]!
}
type Mutation {
  createParticipation(input: CreateParticipationInput!): Participation!
  updateParticipation(
    participationId: ID!
    input: UpdateParticipationInput!
  ): Participation!
}
