enum QuestionStates {
  waiting
  active
  complete
  deleted
}
input CreateQuestionInput {
  eventId: String!
  startDate: DateTime
  endDate: DateTime!
  state: QuestionStates
}
input UpdateQuestionInput {
  startDate: DateTime
  endDate: DateTime
  state: QuestionStates
}
type Question {
  _id: ID!
  startDate: DateTime!
  endDate: DateTime!
  state: QuestionStates!
  updatedAt: DateTime!
  createdAt: DateTime!
}
type Query {
  getQuestions: [Question]!
}
type Mutation {
  setQuestionState(questionId: ID!, state: QuestionStates!): Boolean!
  createQuestion(input: CreateQuestionInput!): Question!
  updateQuestion(questionId: ID!, input: UpdateQuestionInput!): Question!
  deleteQuestion(eventId: ID!, questionId: ID!): Boolean!
}
