input CreateResponseInput {
  questionId: String!
  userId: String!
  value: String!
}
input UpdateResponseInput {
  value: String
}
type Response {
  _id: ID!
  user: User!
  value: String!
}
type SubscribeDeleteResponse {
  _id: ID!
  deleted: Boolean
}
type Query {
  getResponses: [Response]!
}
type Mutation {
  createResponse(input: CreateResponseInput!): Response!
  updateResponse(responseId: ID!, input: UpdateResponseInput!): Response!
  deleteResponse(responseId: ID!): Boolean!
}
type Subscription {
  subscribeResponse(responseId: ID!): Response!
  subscribeDeletedResponse(responseId: ID!): SubscribeDeleteResponse!
}
